import Head from 'next/head'
import Home from '../modules/home'
import axios from 'axios'

const HomePage = ({ cars, manufacturers, colors }) => (
    <div>
      <Head>
        <title>Auto-1 group</title>
        <meta name="description" content="Generated by Auto-1 group" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home carsData={cars} manufacturers={manufacturers} colors={colors} />
      </div>
  )

export default HomePage

export const getServerSideProps = async ({ query: { sort = '', page = 1, color = '', manufacturer= '' } }) => {
  let cars = []
  let manufacturers = []
  let colors = []

  try {
    const [{ data: carsData }, { data: manufacturersData }, { data: colorsData }] = await Promise.all([
      axios(`${process.env.REACT_APP_API_URL}/cars?sort=${sort}&page=${page}&manufacturer=${manufacturer}&color=${color}`), 
      axios(`${process.env.REACT_APP_API_URL}/manufacturers`), 
      axios(`${process.env.REACT_APP_API_URL}/colors`),
    ])

    cars = carsData
    manufacturers = manufacturersData?.manufacturers
    colors = colorsData?.colors

  }catch(error) {
    console.error(error)
  }

  return {
    props: {
      cars,
      manufacturers,
      colors
    }
  }
}